### ISSUE TITLE
incorrect repository structure and name.

### ISSUE THREAD

**Issue by danmarsden** [eledia/moodle-local_qtypestack_synccopies#1]
The moodle code should sit inside the root of the github directory - not inside a folder called local/synccopies - this allows organisations to use git to install your plugin as a submodule or subtree.

Your repository name should also use the standard frankenstyle Moodle naming convention which makes it easy for moodle admins to identify your plugin.

the correct format to use is moodle-{frankenstylepluginname}
eg if your plugin was "mod_attendance" the correct name to use would be: "moodle-mod_attendance"

Github maintains redirects from your old name to the new one which makes this very easy - just hit the "settings" tab on your github repository and the rename repository option should appear near the top.

**Comment by eledia** [comment]
Branch v_41 was newly created. Issues have been resolved there.
