### ISSUE TITLE
frankenstyle naming violations

### ISSUE THREAD

**Issue by danmarsden** [eledia/moodle-local_qtypestack_synccopies#3]
All functions must follow the frankenstyle naming rules
https://moodledev.io/general/development/policies/codingstyle/frankenstyle#function-names

Note this is a blocker for plugins db approval.

**Comment by danmarsden** [comment]
Many of your functions in lib.php will need to be fixed.

**Comment by danmarsden** [comment]
also this one:
https://github.com/eledia/local_qtypestack_synccopies/blob/v_41/local/qtypestack_synccopies/cli/fix_tags.php#L44

but - functions shouldn't be mixed with inline php code - functions should sit in lib or namespaced class files.

**Comment by eledia** [comment]
Branch v_41 was newly created. Issues have been resolved there.
