### ISSUE TITLE
hard-coded user id

### ISSUE THREAD

**Issue by danmarsden** [eledia/moodle-local_qtypestack_synccopies#6]
https://github.com/eledia/local_qtypestack_synccopies/blob/v_41/local/qtypestack_synccopies/cli/create_missing_variantcopies.php#L33

https://github.com/eledia/local_qtypestack_synccopies/blob/v_41/local/qtypestack_synccopies/cli/fix_tags.php#L33

I suspect you should be using a get_admin() style call there.

Hard-coded ids like this are typically plugins db approval blockers.

**Comment by eledia** [comment]
Branch v_41 was newly created. Issues have been resolved there.
